export const ingredients = [
    { value: 'acucar', label: 'Açúcar' },
    { value: 'sal', label: 'Sal' },
    { value: 'pimenta-do-reino', label: 'Pimenta-do-reino' },
    { value: 'azeite-de-oliva', label: 'Azeite de oliva' },
    { value: 'manteiga', label: 'Manteiga' },
    { value: 'farinha-de-trigo', label: 'Farinha de trigo' },
    { value: 'leite', label: 'Leite' },
    { value: 'ovos', label: 'Ovos' },
    { value: 'alho', label: 'Alho' },
    { value: 'cebola', label: 'Cebola' },
    { value: 'tomate', label: 'Tomate' },
    { value: 'arroz', label: 'Arroz' },
    { value: 'batata', label: 'Batata' },
    { value: 'cenoura', label: 'Cenoura' },
    { value: 'pimentao', label: 'Pimentão' },
    { value: 'maionese', label: 'Maionese' },
    { value: 'mostarda', label: 'Mostarda' },
    { value: 'vinagre', label: 'Vinagre' },
    { value: 'molho-de-tomate', label: 'Molho de tomate' },
    { value: 'creme-de-leite', label: 'Creme de leite' },
    { value: 'queijo-parmesao', label: 'Queijo parmesão' },
    { value: 'queijo-mussarela', label: 'Queijo mussarela' },
    { value: 'macarrao', label: 'Macarrão' },
    { value: 'peito-de-frango', label: 'Peito de frango' },
    { value: 'carne-moida', label: 'Carne moída' },
    { value: 'carne-bovina', label: 'Carne bovina' },
    { value: 'carne-de-porco', label: 'Carne de porco' },
    { value: 'peixe', label: 'Peixe' },
    { value: 'camarao', label: 'Camarão' },
    { value: 'bacalhau', label: 'Bacalhau' },
    { value: 'oregano', label: 'Orégano' },
    { value: 'manjericao', label: 'Manjericão' },
    { value: 'alecrim', label: 'Alecrim' },
    { value: 'salsinha', label: 'Salsinha' },
    { value: 'cebolinha', label: 'Cebolinha' },
    { value: 'coentro', label: 'Coentro' },
    { value: 'louro', label: 'Louro' },
    { value: 'canela', label: 'Canela' },
    { value: 'cravo-da-india', label: 'Cravo-da-índia' },
    { value: 'noz-moscada', label: 'Noz-moscada' },
    { value: 'pimenta-calabresa', label: 'Pimenta-calabresa' },
    { value: 'pimenta-do-reino-branca', label: 'Pimenta-do-reino branca' },
    { value: 'cominho', label: 'Cominho' },
    { value: 'curry', label: 'Curry' },
    { value: 'paprica-doce', label: 'Páprica doce' },
    { value: 'paprica-picante', label: 'Páprica picante' },
    { value: 'gengibre', label: 'Gengibre' },
    { value: 'curcuma', label: 'Cúrcuma (açafrão-da-terra)' },
    { value: 'cardamomo', label: 'Cardamomo' },
    { value: 'mostarda-em-po', label: 'Mostarda em pó' },
    { value: 'pimenta-caiena', label: 'Pimenta caiena' },
    { value: 'alho-poro', label: 'Alho-poró' },
    { value: 'aipo', label: 'Aipo (salsão)' },
    { value: 'espinafre', label: 'Espinafre' },
    { value: 'brocolis', label: 'Brócolis' },
    { value: 'couve-flor', label: 'Couve-flor' },
    { value: 'alface', label: 'Alface' },
    { value: 'rucula', label: 'Rúcula' },
    { value: 'agriao', label: 'Agrião' },
    { value: 'pimentao-verde', label: 'Pimentão verde' },
    { value: 'pimentao-vermelho', label: 'Pimentão vermelho'},
    { value: 'pimentao-amarelo', label: 'Pimentão amarelo'},
    { value: 'farinha panco', label: 'Farinha Panco'},
    { value: 'farinha de rosca', label: 'Farinha de rosca'},
    { value: 'frango desfiado', label: 'Frango Desfiado'},
    { value: 'tilápia', label: 'tilápia'},
    { value: 'salmão', label: 'salmão'},
    { value: 'linguado', label: 'linguado'},
    { value: 'bacalhau desfiado', label: 'Bacalhau Desfiado'},
    { value: 'merluza', label: 'Merluza'},
    { value: 'bacon', label: 'Bacon'},
    { value: 'linguiça', label: 'Linguiça'},
    { value: 'presunto', label: 'Presunto'},
    { value: 'chouriço', label: 'Chouriço'},
    { value: 'linguiça-calabresa', label: 'Linguiça calabresa'},
    { value: 'repolho', label: 'Repolho' },
    { value: 'abobrinha', label: 'Abobrinha' },
    { value: 'berinjela', label: 'Berinjela' },
    { value: 'ervilha', label: 'Ervilha' },
    { value: 'feijao-preto', label: 'Feijão preto' },
    { value: 'feijao-carioca', label: 'Feijão carioca' },
    { value: 'lentilha', label: 'Lentilha' },
    { value: 'grao-de-bico', label: 'Grão-de-bico' },
    { value: 'amendoas', label: 'Amêndoas' },
    { value: 'castanha-do-para', label: 'Castanha-do-pará' },
    { value: 'castanha-de-caju', label: 'Castanha de caju' },
    { value: 'nozes', label: 'Nozes' },
    { value: 'avela', label: 'Avelã' },
    { value: 'amendoim', label: 'Amendoim' },
    { value: 'passas', label: 'Passas' },
    { value: 'damasco-seco', label: 'Damasco seco' },
    { value: 'ameixa-seca', label: 'Ameixa seca' },
    { value: 'tamaras', label: 'Tâmaras' },
    { value: 'figo-seco', label: 'Figo seco' },
    { value: 'coco-ralado', label: 'Coco ralado' },
    { value: 'chocolate-em-po', label: 'Chocolate em pó' },
    { value: 'chocolate-meio-amargo', label: 'Chocolate meio amargo' },
    { value: 'chocolate-ao-leite', label: 'Chocolate ao leite' },
    { value: 'chocolate-branco', label: 'Chocolate branco' },
    { value: 'acucar-mascavo', label: 'Açúcar mascavo' },
    { value: 'acucar-demarara', label: 'Açúcar demerara' },
    { value: 'mel', label: 'Mel' },
    { value: 'glucose-de-milho', label: 'Glucose de milho' },
    { value: 'xarope-de-bordo', label: 'Xarope de bordo (maple syrup)' },
    { value: 'leite-condensado', label: 'Leite condensado' },
    { value: 'leite-em-po', label: 'Leite em pó' },
    { value: 'leite-de-coco', label: 'Leite de coco' },
    { value: 'leite-de-amendoas', label: 'Leite de amêndoas' },
    { value: 'iogurte-natural', label: 'Iogurte natural' },
    { value: 'queijo-cottage', label: 'Queijo cottage' },
    { value: 'ricota', label: 'Ricota' },
    { value: 'cream-cheese', label: 'Cream cheese' },
    { value: 'requeijao', label: 'Requeijão' },
    { value: 'catupiry', label: 'Catupiry' },
    { value: 'gorgonzola', label: 'Gorgonzola' },
    { value: 'queijo-brie', label: 'Queijo brie' },
    { value: 'queijo-camembert', label: 'Queijo camembert' },
    { value: 'queijo-provolone', label: 'Queijo provolone' },
    { value: 'queijo-cheddar', label: 'Queijo cheddar' },
    { value: 'queijo-coalho', label: 'Queijo coalho' },
    { value: 'queijo-feta', label: 'Queijo feta' },
    { value: 'queijo-gruyere', label: 'Queijo gruyère' },
    { value: 'queijo-pecorino', label: 'Queijo pecorino' },
    { value: 'queijo-gouda', label: 'Queijo gouda' },
    { value: 'queijo-edam', label: 'Queijo edam' },
    { value: 'queijo-roquefort', label: 'Queijo roquefort' },
    { value: 'queijo-emmental', label: 'Queijo emmental' },
    { value: 'queijo-stilton', label: 'Queijo stilton' },
    { value: 'queijo-mascarpone', label: 'Queijo mascarpone' },
    { value: 'creme-de-ricota', label: 'Creme de ricota' },
    { value: 'sour-cream', label: 'Sour cream' },
    { value: 'molho-ingles', label: 'Molho inglês' },
    { value: 'molho-de-soja', label: 'Molho de soja (shoyu)' },
    { value: 'molho-teriyaki', label: 'Molho teriyaki' },
    { value: 'molho-barbecue', label: 'Molho barbecue' },
    { value: 'molho-de-ostras', label: 'Molho de ostras' },
    { value: 'molho-de-peixe', label: 'Molho de peixe' },
    { value: 'molho-de-pimenta', label: 'Molho de pimenta' },
    { value: 'molho-pesto', label: 'Molho pesto' },
    { value: 'ketchup', label: 'Ketchup' },
    { value: 'tabasco', label: 'Tabasco' },
    { value: 'gergelim', label: 'Gergelim' },
    { value: 'sementes-de-girassol', label: 'Sementes de girassol' },
    { value: 'sementes-de-abobora', label: 'Sementes de abóbora' },
    { value: 'sementes-de-chia', label: 'Sementes de chia' },
    { value: 'sementes-de-linhaca', label: 'Sementes de linhaça' },
    { value: 'melado-de-cana', label: 'Melado de cana' },
    { value: 'melaço', label: 'Melaço' },
    { value: 'vinagre-balsamico', label: 'Vinagre balsâmico' },
    { value: 'vinagre-de-maca', label: 'Vinagre de maçã' },
    { value: 'vinagre-de-vinho-branco', label: 'Vinagre de vinho branco' },
    { value: 'vinagre-de-vinho-tinto', label: 'Vinagre de vinho tinto' },
    { value: 'vinagre-de-arroz', label: 'Vinagre de arroz' },
    { value: 'maçã', label: 'Maçã' },
    { value: 'banana', label: 'Banana' },
    { value: 'laranja', label: 'Laranja' },
    { value: 'limao', label: 'Limão' },
    { value: 'morango', label: 'Morango' },
    { value: 'framboesa', label: 'Framboesa' },
    { value: 'amora', label: 'Amora' },
    { value: 'mirtilo', label: 'Mirtilo' },
    { value: 'uva', label: 'Uva' },
    { value: 'abacaxi', label: 'Abacaxi' },
    { value: 'melancia', label: 'Melancia' },
    { value: 'melao', label: 'Melão' },
    { value: 'mamao', label: 'Mamão' },
    { value: 'manga', label: 'Manga' },
    { value: 'kiwi', label: 'Kiwi' },
    { value: 'pessego', label: 'Pêssego' },
    { value: 'nectarina', label: 'Nectarina' },
    { value: 'ameixa', label: 'Ameixa' },
    { value: 'caju', label: 'Caju' },
    { value: 'caqui', label: 'Caqui' },
    { value: 'maracuja', label: 'Maracujá' },
    { value: 'abacate', label: 'Abacate' },
    { value: 'pera', label: 'Pêra' },
    { value: 'figo', label: 'Figo' },
    { value: 'goiaba', label: 'Goiaba' },
    { value: 'carambola', label: 'Carambola' },
    { value: 'fruta-do-conde', label: 'Fruta-do-conde (pinha)' },
    { value: 'jaca', label: 'Jaca' },
    { value: 'jabuticaba', label: 'Jabuticaba' },
    { value: 'acerola', label: 'Acerola' },
    { value: 'cupuaçu', label: 'Cupuaçu' },
    { value: 'graviola', label: 'Graviola' },
    { value: 'cambuci', label: 'Cambuci' },
    { value: 'pitanga', label: 'Pitanga' },
    { value: 'seriguela', label: 'Seriguela' },
    { value: 'açaí', label: 'Açaí' },
    { value: 'buriti', label: 'Buriti' },
    { value: 'guarana', label: 'Guaraná' },
    { value: 'castanha-de-baru', label: 'Castanha de baru' },
    { value: 'tucuma', label: 'Tucumã' },
    { value: 'pequi', label: 'Pequi' },
    { value: 'inhame', label: 'Inhame' },
    { value: 'mandioca', label: 'Mandioca' },
    { value: 'aipim', label: 'Aipim' },
    { value: 'batata-doce', label: 'Batata-doce' },
    { value: 'batata-baroa', label: 'Batata baroa (mandioquinha)' },
    { value: 'nabo', label: 'Nabo' },
    { value: 'rabanete', label: 'Rabanete' },
    { value: 'abobora', label: 'Abóbora' },
    { value: 'chuchu', label: 'Chuchu' },
    { value: 'quiabo', label: 'Quiabo' },
    { value: 'maxixe', label: 'Maxixe' },
    { value: 'palmito', label: 'Palmito' },
    { value: 'pupunha', label: 'Pupunha' },
    { value: 'jilo', label: 'Jiló' },
    { value: 'taioba', label: 'Taioba' },
    { value: 'hortela', label: 'Hortelã' },
    { value: 'salvia', label: 'Sálvia' },
    { value: 'tomilho', label: 'Tomilho' },
    { value: 'estragao', label: 'Estragão' },
    { value: 'erva-doce', label: 'Erva-doce' },
    { value: 'pimenta-dedo-de-moca', label: 'Pimenta dedo-de-moça' },
    { value: 'pimenta-malagueta', label: 'Pimenta malagueta' },
    { value: 'pimenta-biquinho', label: 'Pimenta-biquinho' },
    { value: 'pimenta-de-cheiro', label: 'Pimenta-de-cheiro' },
    { value: 'wasabi', label: 'Wasabi' },
    { value: 'gengibre-fresco', label: 'Gengibre fresco' },
    { value: 'gengibre-em-po', label: 'Gengibre em pó' },
    { value: 'curry-em-po', label: 'Curry em pó' },
    { value: 'tempero-baiano', label: 'Tempero baiano' },
    { value: 'tempero-caseiro', label: 'Tempero caseiro' },
    { value: 'paprica-defumada', label: 'Páprica defumada' },
    { value: 'alcaravia', label: 'Alcaravia (cominho-do-campo)' },
    { value: 'zimbro', label: 'Zimbro' },
    { value: 'mostarda-em-graos', label: 'Mostarda em grãos' },
    { value: 'mostarda-dijon', label: 'Mostarda Dijon' },
    { value: 'alcaparras', label: 'Alcaparras' },
    { value: 'azeitona-verde', label: 'Azeitona verde' },
    { value: 'azeitona-preta', label: 'Azeitona preta' },
    { value: 'tomate-seco', label: 'Tomate seco' },
    { value: 'picles', label: 'Picles' },
    { value: 'geleia-de-frutas-vermelhas', label: 'Geleia de frutas vermelhas' },
    { value: 'geleia-de-morango', label: 'Geleia de morango' },
    { value: 'geleia-de-laranja', label: 'Geleia de laranja' },
    { value: 'geleia-de-pessego', label: 'Geleia de pêssego' },
    { value: 'geleia-de-damasco', label: 'Geleia de damasco' },
    { value: 'doce-de-leite', label: 'Doce de leite' },
    { value: 'goiabada', label: 'Goiabada' },
    { value: 'brigadeiro', label: 'Brigadeiro' },
    { value: 'beijinho', label: 'Beijinho' },
    { value: 'cajuzinho', label: 'Cajuzinho' },
    { value: 'pacoca', label: 'Paçoca' },
    { value: 'pe-de-moleque', label: 'Pé de moleque' },
    { value: 'cocada', label: 'Cocada' },
    { value: 'rapadura', label: 'Rapadura' },
    { value: 'biscoito-de-polvilho', label: 'Biscoito de polvilho' },
    { value: 'pao-de-queijo', label: 'Pão de queijo' },
    { value: 'biscoito-amanteigado', label: 'Biscoito amanteigado' },
    { value: 'biscoito-de-nata', label: 'Biscoito de nata' },
    { value: 'bolo-de-cenoura', label: 'Bolo de cenoura' },
    { value: 'bolo-de-fuba', label: 'Bolo de fubá' },
    { value: 'bolo-de-milho', label: 'Bolo de milho' },
    { value: 'bolo-de-chocolate', label: 'Bolo de chocolate' },
    { value: 'bolo-de-laranja', label: 'Bolo de laranja' },
    { value: 'bolo-de-coco', label: 'Bolo de coco' },
    { value: 'pao-frances', label: 'Pão francês' },
    { value: 'pao-integral', label: 'Pão integral' },
    { value: 'pao-de-forma', label: 'Pão de forma' },
    { value: 'pao-sirio', label: 'Pão sírio' },
    { value: 'pao-italiano', label: 'Pão italiano' },
    { value: 'torrada', label: 'Torrada' },
    { value: 'croissant', label: 'Croissant' },
    { value: 'baguete', label: 'Baguete' },
    { value: 'pao-de-alho', label: 'Pão de alho' },
    { value: 'pao-de-batata', label: 'Pão de batata' },
    { value: 'pao-de-milho', label: 'Pão de milho' },
    { value: 'pao-doce', label: 'Pão doce' },
    { value: 'rosquinha-de-coco', label: 'Rosquinha de coco' },
    { value: 'pao-de-leite', label: 'Pão de leite' },
    { value: 'pao-australiano', label: 'Pão australiano' },
    { value: 'muffin', label: 'Muffin' },
    { value: 'cupcake', label: 'Cupcake' },
    { value: 'brownie', label: 'Brownie' },
    { value: 'cookie', label: 'Cookie' },
    { value: 'churros', label: 'Churros' },
    { value: 'donuts', label: 'Donuts' },
    { value: 'torta-de-maca', label: 'Torta de maçã' },
    { value: 'torta-de-limao', label: 'Torta de limão' },
    { value: 'torta-de-morango', label: 'Torta de morango' },
    { value: 'torta-de-chocolate', label: 'Torta de chocolate' },
    { value: 'quiche', label: 'Quiche' },
    { value: 'empadao', label: 'Empadão' },
    { value: 'coxinha', label: 'Coxinha' },
    { value: 'rissole', label: 'Rissole' },
    { value: 'esfirra', label: 'Esfirra' },
    { value: 'quibe', label: 'Quibe' },
    { value: 'empanada', label: 'Empanada' },
    { value: 'pasteizinhos', label: 'Pasteizinhos' },
    { value: 'cuscuz-paulista', label: 'Cuscuz paulista' },
    { value: 'polenta', label: 'Polenta' },
    { value: 'tapioca', label: 'Tapioca' },
    { value: 'pamonha', label: 'Pamonha' },
    { value: 'curau', label: 'Curau' },
    { value: 'canjica', label: 'Canjica' },
    { value: 'arroz-doce', label: 'Arroz doce' },
    { value: 'sagu', label: 'Sagu' },
    { value: 'mingau-de-milho', label: 'Mingau de milho' },
    { value: 'farofa', label: 'Farofa' },
    { value: 'arroz-carreteiro', label: 'Arroz carreteiro' },
    { value: 'feijoada', label: 'Feijoada' },
    { value: 'moqueca', label: 'Moqueca' },
    { value: 'galinhada', label: 'Galinhada' },
    { value: 'rabada', label: 'Rabada' },
    { value: 'picadinho-de-carne', label: 'Picadinho de carne' },
    { value: 'file-a-parmegiana', label: 'Filé à parmegiana' },
    { value: 'lasanha', label: 'Lasanha' },
    { value: 'fubá', label: 'Fubá'}
];
